# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaGetUser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Auto Layout
  pod 'SnapKit'

  # API Manager
  pod 'Moya'

  # Rx
  pod 'ReactorKit'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Swift Initializer
  pod 'Then'

end
